sudo: required
language: scala
jdk:
  - openjdk11
services:
  - docker

cache:
  directories:
  - $HOME/.m2
notifications:
  flowdock:
    secure: "cqvHuDSaJVytJQGhnhObBcDkp30fznnCfExSYdsPJQu/5GUW0GJEe9zbgnuJWfMy4IaX7MdhagIus20AUJw3YkwJW5YxtBxEyxqRepJ7GdZXrlR4ieG0zdDn+1neljFhZ5Ywo29wN45j4ORqgnjr2pBUuZBSbHTxzj6kHIqwn+w="

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "bvGlpIg67tSDvO5MSISJ/JXCaqg28E/1Vi/C8GQt3/B3YFHdLOidbbEPrh83nUhBR4CWnVGn3dhwJ/Nb3ILFhNzUj2vUBhY7rSq1KWqGOBiO5NOpWHG3HxwCCD2j7cMoQNzuSJCMcSFUuqJ/CCEXNXH1OjrGeBFhXe6xox6HboQ="
    # AWS_SECRET_ACCESS_KEY
    - secure: "eTSVzA0VXXpFoTMGjcQGwOKvWal8qHkrvS0CZYZByIqh8Z9Cq73lrgen/5CekGPIglJhakvK6OZK34r0m0Kisw6SBNA8+yWykmv4cKK0410ZEn/Jr3JBWU8OMdLrEDVQt77eNlIr3QtRpjVLVDPs39VFBgJN63MdlRTq1jVxQ94="

install:
  - export TZ=Europe/Helsinki
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="suoritusrekisteri"
  - nvm install 6
  - npm install bower
  - node_modules/bower/bin/bower update

script: >-
  mvn clean spotless:check install -B -DargLine="-Dlog4j.configuration=file:./src/test/resources/log4j.properties" &&
  mv target/suoritusrekisteri*allinone.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar &&
  jar xf $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar META-INF/native && mv META-INF/native $DOCKER_BUILD_DIR/native_libs &&
  cp -vr src/main/resources/* $DOCKER_BUILD_DIR/config/ &&
  export BASE_IMAGE="baseimage-fatjar-openjdk11:master" &&
  ./ci-tools/common/pull-image.sh &&
  ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME

deploy:
  - provider: script
    script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
    on:
      all_branches: true
