sudo: required
language: scala
jdk:
  - oraclejdk8
services:
  - docker

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "c7UH4Z7pfkuUmdqWOYJPbdMSKeO+NFrQ6Oo6GUfCeeGkItAHC8NMcnG5WYgWk/xgdHop0SrQiZAxC+T68EcNK0xd18J3QYx3PLK+wAqM++DDwekpr5mTSbRnAlZC9gklt4sgvRGYPPJDfW1WRTBpDErV3/PnnL/e3JTA5JYcIxQ="
    # AWS_SECRET_ACCESS_KEY
    - secure: "KFQkcuQoI3443pw4/3t8DbSZyNULnA0dkjPI4cS8z7BuzdSr0rbh2Panqqy8WlmVozPtYzgHqOVTbBzmfWaBRQ7FyXImEzTocb5J0/04hNJv5NP8m/JizQGGsGTIpExqFta87R3Pitwz2pRpkFxL4k1d6r1MCVdIlr3xV8pFX1k="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh

script:
  - mvn clean install -DskipTests -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}
