name: Suoritusrekisteri

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          java-version-file: '.java-version'
          distribution: 'corretto'
          cache: 'maven'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Run NPM
        run: |
          npm install bower
          node_modules/bower/bin/bower update
          npm -v
          node -v

      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Helsinki"

      - name: Build with Maven
        run: |
          chrome --version
          mvn clean spotless:check install -B -DargLine="-Dlog4j.configuration=file:./src/test/resources/log4j.properties"

      - uses: actions/cache@v4
        id: restore-build
        with:
          path: |
            target
          key: ${{ github.sha }}

  deploy-container:
    needs: [build]
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@main
    with:
      application: suoritusrekisteri
      base-image: baseimage-fatjar-openjdk11:master
      configfolder: src/main/resources/oph-configuration
      jarfile: suoritusrekisteri*allinone
      native-libraries: true
    secrets:
      AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}
