name: Suoritusrekisteri

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '6'
      - run: npm install bower
      - run: node_modules/bower/bin/bower update
      - name: Build with Maven
        run: mvn clean spotless:check install -B -DargLine="-Dlog4j.configuration=file:./src/test/resources/log4j.properties"